apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: htpasswd2-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgCWIwrn7rsrw1gq8sb9B+Zpc9s3JhTBSGHjwediYK9oYSTbzehYG1LO6L/EaNUPRenJg93XekG9YEoNszIVaslrS/nuRoO66lQuHBvh9HTlgG8jBuLyKAe0ez4MFpVd9ZYdhfyNkkBs/5oc7Iq3WHDSFgc/jwm9s0sXpW5pkx+U+0dAgLviWx0ksBRw5XtHBzMwiJs7Br9D8FY18PfBAu8uTn7NY74ttsPx3w+QuVBSuGm9O5SKK/+bhQT3XiGvyrRz/nIzfU2APyiY3IOpbP4N6bt/H4S7LWe2iv+G6lQwpqe21q6di7dh9jJhavDOYlGicr4KH3GWYocv7ofZRWeqQVYyQMGM03WOdAUJnEtz5ePqu6tTAD4FIKcWjgBSYeAyY/24RQaerGMJyS5U+5Q2yyStiKhCMy37cjfMY+QGq92kEacecSFKCiaLVEKmp+JJP6WRJ5M7QF/mrmojaf8LyOYC7LD2wCfdc6W9P6ptN/qH8EulxU2lAsc4fCfnBgTGhRDtEl5zHUo63yKA8U+PflkC4BU+oKaRWK6/oQWqM9H/Z+5Lk5U8NqsXPtwekP1BcqcOHpulSGMpgvTwmiyanYLQQQkdKMN41BmxmlhLz97eNu220x8j8+SJIBsPdjyu5RQqcSx5rMW5AUmYwifhfXBZdNqVLVJwVopEWXtHqOTi8TOkSQ6hOZuftOYG32MdwFti4JwvsaRgyjRp+xHpboMnKnDA6Cqcn+vb36+LGjjr5dD+evcJ6jgKRumH95UvchFKa3Jqk3XnYC8BJ6IhW96C
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: htpasswd2-secret
      namespace: openshift-config

