apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: htpasswd2-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAtylIBXXW04uOz5IA/vWWZ7XFdVMHcu+34NVTp+NBvnwVnOS9MAbcawxGSzsUdGq+nuV6ly6V+NdCGnS++31+GBKvRL6CdUOMeAJhuzOfMvr0gUplcaQp8cIESkwQ3yqSt86Yv0Q6omfMTDcU9RKPSTU1xjOW3ZkfNJI2CV110/7fkNytbKgu6C8M0W5aS7CQryf8ktZSU6rk9Zi47AmkNIu3MnVmeYYtog1LZJnGzbxQmZZON/i2CLz3ZEBr6sNXZziOBBgwJ4xTKQEQ7CQpX1fUMfNYNkp06laGDxh03HZ5hWYuq7vbFv2CgYSiyLAP12dzr1/I7H2Q0WvOlAT3IuEKw4RlgXfoZ5m9pUi45C3/g0HPygUNpo7OGFEJd5/M+R0fVljDnW9jOCItVmdrgfEp08nw48navgwNsPFWOlsYE41zHf+JF/E79BSmuwq064ZnVABIcEwk+FDQwluN5hstlfa80PH0NryewW8/c6oemr3gOhf9PpqznN53aiyeneaZADnQC8YpL+Ed72qM4vRiiyrcLf9YdFtSolDLBJeQ5oit06hyyf77BZfyXmEZ8xSWjGE0HzxL25tARlCcdE8sRU6JNOhKwslSKacO+7vH4ZPCIiDv34MoDr66o7gEpyiGaGq2uWX/+4VwtNqcc6SYfVFPCNwLzwSY0yEpd+2JO2h4xa1zSu5OlzOW+NVwwiTjVR/WSMv/aby0bsW3ZlYX5xCGFDPa4hFL/P5QYpYlC2012XB2JlmUYeOoPZ+otjK740ZnRrL3CcuySz1SzJ1+B
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: htpasswd2-secret
      namespace: openshift-config

