apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: htpasswd2-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAJVLpimxzZCk70jWDWqESn+G/KBEQnPmc0L26lUmB2tsXTAMHo8TS1fS5mWvm8WWewWoGrxJTlpQkGpVvR44Ue6IX4hluj8F4PBSyRlfA6hd5JrLJswCZ0n14RWAblhvfwYZZ+AsJ5zvuvtsjMs8OVqeFPrbedYbJeKJ7ADg2LbdYnZHOxvAxiG1k9clVK8+mutqEI+PP/7SAl4mqVBfgz7mm79XS9tIeEj71Xxg6dJdiYBJHqXSMen3AbLghCZUtMoE5iEXrp98/N2vzU3bxCQwo0KGPe6k+3Yfae0N0D9bBLamFuG1P+QPWuX5C9iAJVURJiTOvn72A6NxNsZa2OPfVF2ii3/1iBKwCqQwtl2N8JLZFiV91XXJL454xIPub8DkOyS3K5iN481l5xWptl0gwplydt7TmzSqgtCtLZYTyGDPqir2aqx0SStxZNm9hnuIdWNWnfkTRkwsFjRU8E0iH0ZjqY9pX4xw4nZj4b4i2TfVGR8xz6SJsS787ZuwLJT8+HmMDSDLK68Tb0h39l/rgIX2OT+I2pkv8vziUA4P0cTtvdErvgxXpdz7TLdl1HKl1/V2V6tXoPyuyvoC8xUW4J1bovG+aOi3gE4M8JYEv5BaVvDZeZA9942B10leEz3JcmX0+cqoyaszSQZPycV/9nR8jBV1SqBTnLVntrzxFUZ+dwihjYNzxcIUEMTVdIt2u6xDbRBBrxg3ptILPv7HOGZ7o39pt+WLGMfHekZmx7JojAuzY+zwaQr9lnfQxv/0gqSQnqzCZS6MsKq8gQCal5
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: htpasswd2-secret
      namespace: openshift-config

