apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/sclorg/nodejs-ex.git
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"test-app:latest","namespace":"test-app"},"fieldPath":"spec.template.spec.containers[?(@.name==\"test-app\")].image","pause":"false"}]'
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: test-app
    app.kubernetes.io/component: test-app
    app.kubernetes.io/instance: test-app
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: sample-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 14-ubi7
  name: test-app
  namespace: test-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app
        deploymentconfig: test-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/test-app/test-app@sha256:314d66529dff06ec906a868c43ea3118efaa8e95f1c66ac8db40428461cfa88a
        imagePullPolicy: Always
        name: test-app
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
