apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-user-app
  labels:
    gitops.ownedBy: cluster-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/prometheus-user-app
    repoURL: https://github.com/caseyrobb/cluster-config-gitops
    targetRevision: master
  project: cluster-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
