apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  source:
    path: sealed-secrets-operator/overlays/default
    repoURL: https://github.com/redhat-cop/gitops-catalog.git
    targetRevision: main
  project: cluster-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
