apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/sealed-secrets/overlays
    repoURL: https://github.com/caseyrobb/cluster-config-gitops
    targetRevision: main
  project: cluster-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
