apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - htpasswd-sealed-secret.yaml
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.5/controller.yaml
